@echo off
set REPO_URL=https://github.com/rothaa/Monyrotha.git
echo Adding remote...
git remote add origin %REPO_URL% || git remote set-url origin %REPO_URL%
echo Adding files...
git add .
echo Committing...
git commit -m "Pushing portfolio code to Monyrotha repository"
echo Pushing...
git push -u origin main || git push -u origin master
echo Done.
